run:
	@./manage.py runserver 0.0.0.0:8000

shell:
	@./manage.py shell

dbshell:
	@./manage.py dbshell

test:
	./manage.py test actionlog resources projects releases teams --settings=settings_test

static:
	@./manage.py collectstatic
